config/routes.rb
Rails.application.routes.draw do
  root to: "questions#index"

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :questions do
    resources :choices

    patch '/answer' => 'questions#answer'
  end

  get 'my_questions' => 'questions#me'
  get 'answered_questions' => 'questions#answered_questions'
end

app/models/answered_question.rb
class AnsweredQuestion < ApplicationRecord
  belongs_to :user
  belongs_to :question
  belongs_to :choice
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :choices
  accepts_nested_attributes_for :choices

  scope :published, -> { Question.joins(:choices).where(choices: { correct_answer: true}) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  def new
    @question = Question.find(params[:question_id])
    @choice = @question.choices.new(params[:choice])
  end

  def create
    @question = Question.find(params[:question_id])
    @choice = @question.choices.create(text: params[:choice][:text], correct_answer: params[:choice][:correct_answer])

    redirect_to question_path(@question)
  end

  def destroy
    @question = Question.find(:question_id)
    @choice = @question.choices.find(params[:id])
    @choice.destroy

    redirect_to question_path(@question)
  end

  private
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @questions = Question.published
  end

  def show
    @choices = @question.choices
    @answered = AnsweredQuestion.find_by(user_id: current_user.id, question_id: @question.id)
  end

  def new
    @question = current_user.questions.new
  end

  def create
    @question = current_user.questions.build(question_params)

    if @question.save
      redirect_to @question, notice: "Question was successfully created"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to @question, notice: "Question was successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    @question.destroy
    redirect_to root_path
  end

  def answer
    @question = Question.find(params[:question_id])
    @choice = Choice.find(params[:question][:choice][:id])

    AnsweredQuestion.create(user_id: current_user.id, question_id: @question.id, choice_id: @choice.id)

    if @choice.correct_answer
      redirect_to @question, notice: "Correct"
    else
      redirect_to @question, notice: "Wrong"
    end
  end

  def me
    @questions = Question.where(user_id: current_user.id)
  end

  def answered_questions
    @answered_questions = AnsweredQuestion.where(user_id: current_user.id)
    @questions = Question.where(id: @answered_questions.pluck(:question_id))
  end

  private

  def question_params
    params.require(:question).permit(:title)
  end

  def find_question
    @question = Question.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/choices/new.html.erb
<%= form_for([@question, @question.choices.build]) do |f| %>
  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_field :text, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :correct_answer %>
    <%= f.radio_button :correct_answer, true %>true
    <%= f.radio_button :correct_answer, false %>false
  </div>
<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TriviaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Trivia</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "Questions", root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "My questions", my_questions_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "My Answered Questions", answered_questions_path, class: 'nav-link' %>
          </li>
        </ul>
        <% if current_user %>
          <form class="form-inline my-2 my-lg-0">
            <%= link_to('Sign out', destroy_user_session_path, method: :delete) %>
          </form>
        <% else %>
          <form class="form-inline my-2 my-lg-0">
            <%= link_to('Sign In', new_user_session_path) %>
            <%= link_to('Sign Up', new_user_registration_path) %>
          </form>
        <% end %>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<div>
  <h4>Question Text</h4>
  <%= form_for @question do |f| %>
    <%= f.text_field :title %>
    <%= f.submit "Create Question" %>
  <% end %>
</div>

app/views/questions/answered_questions.html.erb
<h2>Questions I've Answered</h2>
<div class="questions_container">
  <% @questions.each do |question| %>
    <div class="question">
      <h2><%= link_to question.title, question %></h2>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>
<%= render 'form' %>

app/views/questions/index.html.erb
<h1>Questions</h1>
<div class="questions_container">
  <% @questions.each do |question| %>
    <div class="question">
      <h2><%= link_to question.title, question %></h2>
    </div>
  <% end %>

  <%= link_to "Create New Question", new_question_path %>
</div>

app/views/questions/me.html.erb
<h2>Questions I've Asked</h2>

<div class="questions_container">
  <% @questions.each do |question| %>
    <div class="question">
      <h2><%= link_to question.title, question %></h2>
    </div>
  <% end %>

  <%= link_to "Create New Question", new_question_path %>
</div>

app/views/questions/new.html.erb
<h1>Create New Question</h1>
<%= render 'form' %>

app/views/questions/show.html.erb
<div class="question_container">
  <h1><%= @question.title %></h1>
  <h5>Asked by: <%= @question.user.name %>

  <% if @question.user_id == current_user.id %>
    <%= link_to "Edit Question", edit_question_path %>
    <%= link_to "Add Choices",  new_question_choice_path(@question.id) %>
  <% else if !@answered %>
    <%= form_for @question, url: question_answer_path(@question) do |f| %>
      <% @choices.each do |choice| %>
        <%= f.fields_for choice do |ff| %>
          <%= ff.radio_button :id, choice.id, checked: false  %><%= choice.text %>
        <% end %>
      <% end %>
      <%= f.submit "Answer" %>
    <% end %>
  <% else %>
    <h4>You've answered this question already</h4>
    <% end %>
  <% end %>
</div>